### ISSUE TITLE
Consider transparently replacing `/` with `\` on Windows in executable path

### ISSUE THREAD

**Issue by goderbauer** [google/process.dart#19]
See https://github.com/flutter/flutter/pull/13978#issuecomment-356707090.

That way it wouldn't matter if you accidentally pass a Linux-like executable path with `\` as path separator on a Windows system. It would just work.

Not sure what the implications of this are. Is there ever a reason why you want to keep a `\` in an executable path on Windows?

**Comment by tvolkert** [comment]
In the case that spawned this bug, the problem stems from the mismatch of trying to use a fake file system with a real process manager.  Since the goal in general is to make the tests hermetic, the test should have used a mock process manager, which wouldn't have suffered from the Windows-specific path issue.

Closing this, since I think real process managers should be able to safely assume that paths passed to them are correct for the platform.

Note that I could envision a `MethodProcessManager` that would be this package's counterpart to `MemoryFilesystem`.  It would allow callers to define executable paths and map them to Dart functions.
